### ISSUE TITLE
tienes que tener 2 clases repository

### ISSUE THREAD

**Issue by JoTerrance** [EmmaPeel68/Servlet#18]
// Borrado
	public void deleteLanguage(int IdIdioma) {
		Connection conn = manager.open(jdbcUrl);
		PreparedStatement preparedStatement = null;
		try {
			preparedStatement = conn.prepareStatement("DELETE FROM IDIOMA WHERE IDIDIOMA = ?");
			preparedStatement.setInt(1, IdIdioma);

			preparedStatement.executeUpdate();

			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		manager.close(conn);
	}
	
	public void deleteCountry(int IdIdioma) {
		Connection conn = manager.open(jdbcUrl);
		PreparedStatement preparedStatement = null;
		try {

			preparedStatement = conn.prepareStatement("DELETE FROM PAIS WHERE IDIOMA = ?");
			preparedStatement.setInt(1, IdIdioma);

			preparedStatement.executeUpdate();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		manager.close(conn);
	}

separa en 2 clasees repository, una para paises y otra para idiomas

**Comment by EmmaPeel68** [comment]
Done
