### ISSUE TITLE
gigantesco refactoriza

### ISSUE THREAD

**Issue by JoTerrance** [EmmaPeel68/Servlet#19]
este metodo sigue siendo gigantesco
hace varias cosas busca en la base de datos y despues inserta
debe hacer lo que dice y solo lo que dice, insert.....
debes crear otros metodos tipo search o lo que necesites y luego en el service, si que llamas a cada una de la piezas pequeñitas del repository
service une las piezas del puzle que esta compuesto por metodos PEQUEÑITOS de repository

// insert
	public void insert(Form formulary) {
		Connection conn = manager.open(jdbcUrl);
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		int id = 0;
		try {
			preparedStatement = conn.prepareStatement("SELECT * FROM IDIOMA WHERE IDIOMA = ?");
			preparedStatement.setString(1, formulary.getLanguage());
			System.out.println(preparedStatement);
			System.out.println(formulary.getLanguage());
			resultSet = preparedStatement.executeQuery();
			if (!resultSet.next()) {
				preparedStatement = conn.prepareStatement("INSERT INTO IDIOMA (IDIOMA)" + "VALUES (?)");
				preparedStatement.setString(1, formulary.getLanguage());
				preparedStatement.executeUpdate();
			}

			preparedStatement = conn.prepareStatement("SELECT * FROM IDIOMA WHERE IDIOMA = ?");
			preparedStatement.setString(1, formulary.getLanguage());
			System.out.println(preparedStatement);
			System.out.println(formulary.getLanguage());
			resultSet = preparedStatement.executeQuery();
			while (resultSet.next()) {
				id = resultSet.getInt(1);
				System.out.println(id);
			}

			preparedStatement = conn.prepareStatement("INSERT INTO PAIS (PAIS,IDIOMA)" + "VALUES (?,?)");
			preparedStatement.setString(1, formulary.getCountry());
			preparedStatement.setInt(2, id);
			preparedStatement.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
		close(preparedStatement);
		manager.close(conn);
	}

**Comment by EmmaPeel68** [comment]
Done
