### ISSUE TITLE
clase padre para los dos repository

### ISSUE THREAD

**Issue by JoTerrance** [EmmaPeel68/Servlet#24]
haz una clase repository padre que contenga estos metodos compartidos y asi podemos dejar repositoryCountry y repositoryLanguage mas pequeñito

private static final String jdbcUrl = "jdbc:h2:file:./src/main/resources/test";
	ConnectionManager manager = new ConnectionH2();

	private void close(PreparedStatement prepareStatement) {
		try {
			prepareStatement.close();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}

	private void close(ResultSet resultSet) {
		try {
			resultSet.close();
		} catch (SQLException e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}

**Comment by EmmaPeel68** [comment]
Done
