### ISSUE TITLE
refactoriza este engendro y hazlo mas corto

### ISSUE THREAD

**Issue by JoTerrance** [EmmaPeel68/Servlet#8]
// insert
	public void insert(Form formulary) {
		Connection conn = manager.open(jdbcUrl);
		PreparedStatement preparedStatement = null;
		ResultSet resultSet = null;
		int id=0;
		try {
			preparedStatement = conn.prepareStatement("SELECT * FROM IDIOMA WHERE IDIOMA = ?");
			preparedStatement.setString(1, formulary.getLanguage());
			System.out.println(preparedStatement);
			System.out.println(formulary.getLanguage());
			resultSet = preparedStatement.executeQuery();
			if(!resultSet.next()){	
				preparedStatement = conn.prepareStatement("INSERT INTO IDIOMA (IDIOMA)" +
						"VALUES (?)");
				preparedStatement.setString(1, formulary.getLanguage());
				
				preparedStatement.executeUpdate();
				
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}finally {
			
			try {
				preparedStatement = conn.prepareStatement("SELECT * FROM IDIOMA WHERE IDIOMA = ?");
				preparedStatement.setString(1, formulary.getLanguage());
				System.out.println(preparedStatement);
				System.out.println(formulary.getLanguage());
				resultSet = preparedStatement.executeQuery();
				while(resultSet.next()){	
					
					id = resultSet.getInt(1);
					System.out.println(id);
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}finally {
				try {
					preparedStatement = conn.prepareStatement("INSERT INTO PAIS (PAIS,IDIOMA)" +
							"VALUES (?,?)");
					preparedStatement.setString(1, formulary.getCountry());
					preparedStatement.setInt(2, id);
					preparedStatement.executeUpdate();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
			}
			
				
			}
			close(preparedStatement);
		
		
		
		manager.close(conn);
	}

**Comment by EmmaPeel68** [comment]
Done
